### ISSUE TITLE
Shows rendered html instead of html code in result view

### ISSUE THREAD

**Issue by teo1978** [Viper-7/Deployable-PHP-Codepad#5]
![Screenshot from 2013-01-08 00:03:58](https://f.cloud.github.com/assets/542107/48749/9e3d6464-591e-11e2-8969-9377f8d0e5bd.png)

The screenshot is self-explanatory.

You should see "<p>Hi</p>" where you see "Hi".

**Comment by teo1978** [comment]
By the way I'm almost sure this is a recent regression

**Comment by DaveRandom** [comment]
Pretty certain this is a by-design non-issue, if I understand what you are saying correctly - do you mean you are expecting to see `<p>Hi</p>` HTML source instead of the rendered version?

This is the way the reworked front end works. If you want to view the generated source code, view the source of the iframe, or place your output in a `<pre>` tag and pass it through `htmlspecialchars()`.

Apologies if I misunderstood what you are saying.

**Comment by teo1978** [comment]
Ok, you understood perfectly. Yes, I expected to see the HTML source as it is the way it used to work in most codepad-like sites I've seen. But hey, the new design makes a lot of sense as long as it is all in an iframe so that one can view the iframe's source code in the browser. Cool.

Now a feature-request/suggestion would be to allow the user to switch between the two modes, so as to not depend on the browser's ability to show an iframe's source code (do _all_ browser have that option?)

Sorry for the bogus bug report.
